# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

require:
  - ./lib/rubocop/cop/homecart/service_class_name

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable

RSpec/ExampleLength:
  Max: 8

RSpec/MultipleExpectations:
  Max: 5

Homecart/ServiceClassName:
  Enabled: true
